CREATE USER 'miam'@'%' IDENTIFIED BY 'wJsYBGR74BMa4ups';
GRANT USAGE ON *.* TO 'miam'@'%' IDENTIFIED BY 'wJsYBGR74BMa4ups' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `miam`.* TO 'miam'@'%';
