CREATE USER 'miam'@'localhost' IDENTIFIED BY 'test';
GRANT USAGE ON *.* TO 'miam'@'localhost' IDENTIFIED BY 'test' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `miam`.* TO 'miam'@'localhost';
FLUSH PRIVILEGES;